services:
  ollama:
    build:
      context: .
      args:
        OLLAMA_MODEL: qwen2.5:7b
    user: root
    ports:
      - 11434:11434
    environment:
      - OLLAMA_HOST=0.0.0.0
      - NVIDIA_VISIBLE_DEVICES=all
      - OLLAMA_MODEL=qwen2.5:7b
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data:
